from io import BytesIO
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


def generate_pdf_report(file_name: str, scan_date: datetime, threat_score: int, ai_prediction: str, details: dict | None = None) -> bytes:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(colors.HexColor("#06b6d4"))
    c.drawString(72, height - 72, "AI Cyber Shield Report")

    c.setStrokeColor(colors.HexColor("#0ea5e9"))
    c.setLineWidth(2)
    c.line(72, height - 82, width - 72, height - 82)

    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)
    c.drawString(72, height - 120, f"File name:")
    c.drawString(180, height - 120, file_name)

    c.drawString(72, height - 140, "Scan date:")
    c.drawString(180, height - 140, scan_date.strftime("%Y-%m-%d %H:%M:%S"))

    c.drawString(72, height - 160, "Threat score:")
    c.drawString(180, height - 160, str(threat_score))

    c.drawString(72, height - 180, "AI prediction:")
    c.drawString(180, height - 180, ai_prediction)

    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.HexColor("#0f766e"))
    c.drawString(72, height - 220, "Analysis Details")
    c.setFont("Helvetica", 11)
    c.setFillColor(colors.black)

    line_y = height - 240
    if details:
        for key, value in details.items():
            c.drawString(84, line_y, f"{key}:")
            c.drawString(220, line_y, str(value))
            line_y -= 18
            if line_y < 72:
                c.showPage()
                c.setFont("Helvetica", 11)
                line_y = height - 72
    else:
        c.drawString(84, line_y, "No additional details provided.")

    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawString(72, 48, "Generated by the AI Cyber Shield backend")

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer.read()
